// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNZzGxoE-c8KEqe701vGOx0y7aKzQdiw4',
    appId: '1:843527900560:web:d593336179eb5390de7715',
    messagingSenderId: '843527900560',
    projectId: 'notesapp-fe555',
    authDomain: 'notesapp-fe555.firebaseapp.com',
    storageBucket: 'notesapp-fe555.firebasestorage.app',
    measurementId: 'G-5VB98CR96K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLKB4qV7lWqFpF0NUjNIBOr88XFtmLxNE',
    appId: '1:843527900560:android:e3b3f01607b11a69de7715',
    messagingSenderId: '843527900560',
    projectId: 'notesapp-fe555',
    storageBucket: 'notesapp-fe555.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNZzGxoE-c8KEqe701vGOx0y7aKzQdiw4',
    appId: '1:843527900560:web:4a331ec3941c3b58de7715',
    messagingSenderId: '843527900560',
    projectId: 'notesapp-fe555',
    authDomain: 'notesapp-fe555.firebaseapp.com',
    storageBucket: 'notesapp-fe555.firebasestorage.app',
    measurementId: 'G-MDZNNRBSXE',
  );
}
